### ISSUE TITLE
Support coloring each byte by its category, like Hexyl

### ISSUE THREAD

**Issue by roryokane** [HexFiend/HexFiend#181]
The command-line hex viewer [Hexyl](https://github.com/sharkdp/hexyl/blob/master/README.md) has an interesting feature: it “uses a colored output to distinguish different categories of bytes (NULL bytes, printable ASCII characters, ASCII whitespace characters, other ASCII characters and non-ASCII).”

![old version of Hexyl displaying the bytes of a PNG file](https://i.imgur.com/MWO9uSL.png)

I think this feature would help me understand files more quickly when using Hex Fiend.

The feature would have to be optional so as not to clash with the existing manual “Highlight Selection” feature. And the colors will have to be carefully chosen so as not to clash with the white-and-blue striped background or the user’s text highlight color. Note that the existing highlighting feature changes the background color of text, while this coloring feature would change the text color.

Since null bytes are greyed-out with these colors, this might make the Hide Null Bytes feature unnecessary.

**Comment by kainjow** [comment]
So it just uses an arbitrary color theme for byte types? Seems like it’d be easy to do, just harder to choose colors, while supporting dark mode. Probably would need to be heavily customizable. Basically an extension of the current grayscale support. Maybe instead of Color Bytes doing only grayscale it could have theme support and grayscale could be a built-in one.

**Comment by kainjow** [comment]
After taking a look at the source again, it's a little trickier than I originally thought, since there's already support for a custom background color per byte, but not foreground color, as the text characters are drawn separately and drawn multiple characters at a time, so it'd have to be broken up into per-character drawing. I started experimenting with a hack, but will need to think through it more.

**Comment by kainjow** [comment]
I implemented an experimental version in 6db0ae0458f5bb7fe118c3a61cf3976ccc20161f

The colors only look good in dark mode currently:

<img width="525" alt="screen shot 2019-01-23 at 9 34 24 pm" src="https://user-images.githubusercontent.com/271035/51656696-fd5eae80-1f56-11e9-8917-ed33d4fb6478.png">

You can turn it on from the command line via `defaults write com.ridiculousfish.HexFiend ColorBytes2 -bool true`

The code had to be changed from drawing multiple characters at a time (all using the same font color) to only one at a time when this mode is enabled, so it slows down noticeably.

**Comment by jeromectm** [comment]
This feature would be great, but it really needs to be customizable (a theme file in the Application Support folder?) to define a custom color (or pair of colors for light/dark mode) for any range of byte values

**Comment by kainjow** [comment]
Agreed, theme support would definitely be implemented.

**Comment by wader** [comment]
Maybe colorize based on template field/section somehow would be interesting also?

**Comment by bwiggs** [comment]
HexFiend is a terrific tool, thanks for all the great work! I wanted to add +1 for byte colorization.

I recently participated in a CTF and one of the challenges was to find a flag amongst a file full of noise. The flag turned out to be an ascii string like `Flag{M4g1c_fL4g_5Tr!ng}`, but each byte was spread out amongst an ocean of non-ascii bytes. Using Hexyl and it's byte color coding made the flag immediately jump out. I thought it was a neat use of visualization of binary data to win the day.

**Comment by kainjow** [comment]
Made more progress on this in the `colorbytes2` branch. I rebased on master and performance was much better than last time I worked on this. Then again, I recently upgraded to an M2 MBR from the Intel 12" MBA 🙂. I did make some minor performance improvements. So far it seems usable enough for me.

Current theme is based on Hexyl, which I installed from Homebrew. I added a "Bright" version that uses macOS's "system" color variants. JSON5 is used for the file format, so this is limited to macOS 12+ which introduced the ability to parse JSON5.

<img width="519" alt="latest" src="https://github.com/HexFiend/HexFiend/assets/271035/c9a5d12f-0288-4f16-b381-c708384d82eb">

```json5
{
   dark: {
       "null": 0x999999,
       "printable": "systemCyan",
       "whitespace": "systemGreen",
       "other": "systemGreen",
       "extended": "systemYellow",
   },
   light: {
      ...
   }
}
```

Need to organize the code and add UI. Also thinking about removing the existing grayscale color bytes feature, and replacing it with this. Maybe later background color customization can be added.
