### ISSUE TITLE
templates improvements

### ISSUE THREAD

**Issue by jeromectm** [HexFiend/HexFiend#193]
A few suggestions to improve the templates:

- when I select some data in the hex or text view, it would be great if the corresponding value(s) in the template were highlighted (and scrolled to be visible)

- it would be great to allow selecting multiple values (at least contiguous, even better also discontiguous) in the template, and highlight the corresponding bytes in the other views; also "copy values" would copy the values of all selected values. And finally, add a "copy labels and value" would copy structured text, with indented sections

- maybe you could add builtin support for posix dates (although we can use clock: `entry "posix date" [clock format [uint32] -format "%d/%m/%Y %H:%M:%S"]`; but this does not use the system's date format, and when I select the value in the template, the corresponding bytes are not highlighted in the other views)

- instead of a timeout, show a progress dialog (even if it is indeterminate) with a stop button when evaluating the template is slow. And if possible, use the partial result of the template if its execution has been stopped.

**Comment by kainjow** [comment]
I added `unixtime32` and `unixtime64` in 1f8de98415ef0de73f338bb56bbcfd4181186df0. They both take an optional label argument.

I looked briefly into whether Tcl scripts can be terminated during evaluation, but didn't see any clear solution. I think the only way to cleanly support this would be to evaluate the script in another process, but that would require either using IPC for communication (slow), or to add a "request" to stop, which would require locking (to prevent further changes), then serialize the existing results and pass them back somehow (IPC or stdout). While that would be a nice to have, I'd rather focus on performance improvements. Let's see if the cstr command helps you out. Otherwise we can see what else is being slow. Are you using a large file?

**Comment by jeromectm** [comment]
Thanks for `unixtime32`! And agreed, it's better to focus on performance improvements; see my comment for #191

**Comment by zardini123** [comment]
Under template improvements, would 010 Editor binary template files (.bt) be possible to support in the near future, along with .tcl scripts?

**Comment by kainjow** [comment]
@zardini123 I have no plans or 010 Editor files. Hex Fiend's templates already use Tcl.

**Comment by lemnet** [comment]
> instead of a timeout, show a progress dialog (even if it is indeterminate) with a stop button when evaluating the template is slow. And if possible, use the partial result of the template if its execution has been stopped.

> I looked briefly into whether Tcl scripts can be terminated during evaluation, [...]

I'm trying to do a JPG template, but, at a certain point, I have to scan every `[uint8]` to check for `0xFFnn (nn != 00)` and it's really slow... So, i can't go to te end of file without hitting a timeout.

I think that a fonction `goto_next value` would be the easiest for me.
But another way to handle slow template would be to let us control the timeout inside the script with a new command like `timeout time_in_sec`, just like `set_time_limit` in php.

**Comment by kainjow** [comment]
@lemnet what version are you using? Have you tried the latest 2.12 beta?

**Comment by lemnet** [comment]
I was using 2.11.0.
I tried with the last beta (2.12) and there is no more timeout.

**Comment by kainjow** [comment]
Some of these suggestions have been implemented, but no plans for the remaining. Please create a new issue per topic for future suggestions. thanks.
