### ISSUE TITLE
Templates missing

### ISSUE THREAD

**Issue by eproxus** [HexFiend/HexFiend#245]
Just installed 2.12 and the templates folder is empty. The release notes show that some templates should be included, are those missing from the download or do they have to be manually installed?

**Comment by gingerbeardman** [comment]
Get them here: https://github.com/ridiculousfish/HexFiend/tree/master/templates

**Comment by kumowoon1025** [comment]
I presume it mentions them since they are in the source tarball. (Not the dmg where you just drag the app to install)

**Comment by eproxus** [comment]
Yeah, I kind of expected them to be installed with the app and available in the binary template menu.

**Comment by kainjow** [comment]
Yes, the templates haven't been included in the app. There weren't any in the beginning ;) but now we're starting a decent collection.

I think one of the complications is it'd be nice to be able to edit them, but you can't do that if it's accessing the template from the app bundle. So then we'd need a way to install them. I guess we could have a button or prompt to install the built-in ones, making sure not to overwrite an existing one. I'll have to think about it a little more.

**Comment by eproxus** [comment]
A nice way might be to separate the bundled and self-installed templates in the menu. And if you edit a bundled template via the GUI it could create a copy.

**Comment by kumowoon1025** [comment]
@eproxus I think the standard way to do this is `/Library/Application Support/...` and `~/Library/Application Support/...`

But imho the more fundamental question is which templates do you include? Currently they are all authored by volunteers, afaik, from publicly available info, some of them from official standards but others from de facto bitstream format specs reverse engineered or from otherwise less-than-official sources.

Which is not to say they are not accurate, but almost certainly they are not complete implementations. So I wonder what it would take for a template to earn the endorsement implied when it is included with the app, even if only  as an example.

**Comment by eproxus** [comment]
I personally would prefer to have them in the app and if they're wrong, report a bug or make a PR to the project. I don't think including them implies they will forever be "perfect" 😄 That would provide more value to me than _not_ including them and making me hunt for them in a git repo somewhere and manually create folders inside hidden OS folders and  move files there and then restart the program.

**Comment by kumowoon1025** [comment]
For sure it would be easier if they were installed automatically, and maybe the template chooser dropdown could be expanded to have a manager type function? (It already has a shortcut to open the template folder and you can refresh from the same menu instead of relaunching the app) But I think for any template that shows up in the menu by default most people's expectation would be that it functions as an accurate and mostly complete parser for the format. Knowing that, I don't know if it would be so simple to curate the list of included templates; specific binary template issues being reported as bugs is a bit too much imo, I know they have been added through PRs, but unless there is an issue with the tcl interpreter itself it shouldn't be considered a bug in Hex Fiend.

**Comment by eproxus** [comment]
Each to their own, I guess. I'm just saying me as a user (only one datapoint of course) would prefer not having to jump hoops to get to the files. And I don't have the expectation that they would be perfect.

**Comment by kumowoon1025** [comment]
@eproxus Just out of curiosity, which templates in the repository are complete enough to be installed automatically when the app launches in your opinion?

**Comment by eproxus** [comment]
@kumowoon1025 Actually, no idea. I just reported this because I saw the release note and wanted to try them out. I only downloaded the PNG template which seemed to work.

**Comment by kumowoon1025** [comment]
I just had a thought, I think It'd be cool to have some kind of UI like Xcode has where you can download simulators and Swift toolchains a la carte, and at least show which templates are available, and make it a one-click install.

**Comment by kumowoon1025** [comment]
Of course this sort of stems from my ulterior motive of pushing for the renovation the overall UI to use (more) standard components, right now the glyph runs and data inspector UI's are like completely custom, it scares me to mess with it as I don't fully understand it. 😅

**Comment by kainjow** [comment]
@kumowoon1025 the data inspector is using standard AppKit controls. Why do you think it’s not?

Now that we have a HF org, maybe the templates could he split into their own repo. It might make them more visible and move PRs and bugs to a separate place.

How about this for a 1.0 design:m to keep things simple:
- Community templates are bundled with the app, embedded as raw files in the app’s bundle resources
- They show in the menu but separated
- Folder structure should be doable with AppKit menus
- On first selection of a community bundled template, show an alert that these are part of the app bundle and to edit the user must copy them to the template folder manually. No UI is given to do this initially.

This should be fairy simple and straightforward to do. Then we can expand from there as we see how it’s used.

Thoughts?

**Comment by kainjow** [comment]
Initial implementation is done with 3c76bc8

<img width="420" alt="image" src="https://user-images.githubusercontent.com/271035/171337087-229f8c72-0d2d-423c-a998-7abd413c92fa.png">
