### ISSUE TITLE
Is there anyway to get current file name in binary templates?

### ISSUE THREAD

**Issue by jjm2473** [HexFiend/HexFiend#313]
I can't find the answer from 
https://github.com/HexFiend/HexFiend/blob/master/templates/Reference.md

**Comment by kainjow** [comment]
Not currently. How are you wanting to use this?

**Comment by jjm2473** [comment]
I want to show a shell command in template that dump range of current file(or show a command that calculate hash in range of the file).

**Comment by kainjow** [comment]
Can any of the existing byte functions work? https://github.com/HexFiend/HexFiend/blob/master/templates/Reference.md#raw-bytes

What kind of hash? Did you see if Tcl provides a function for it already? If not and it's already supported by macOS APIs, we could probably add it fairly easy to HF.

Adding a filename function is kind of a hack as it exposes the underlying data source which isn't always backed by a file, such as disks, extended attributes, and possibly in the future file slices. So you'd need error handling since returning an empty string would be dangerous.

**Comment by jjm2473** [comment]
OK, maybe there is another ways to fit my situation.

I found a bug in HF, that is when I click "Select Bytes" in context menu in template view, then press Command+C, will copy some strangle data to clipboard. I must first click HEX view or Text view, then right click template view, then click "Select Bytes", then press Command+C, clipboard data will be right.

**Comment by kainjow** [comment]
Please create a new issue for that bug. thanks.
