### ISSUE TITLE
Feature Request: Add parsing of Exponential-Golumb Codes

### ISSUE THREAD

**Issue by figgis** [HexFiend/HexFiend#363]
Exp-Golumb is the key mechanism to store data in H.264 bistream format

https://bitstring.readthedocs.io/en/latest/exp-golomb.html

Having support for those in this tool would open up so many possibilities.

**Comment by wader** [comment]
@figgis Hi, i've spent some time decoding bit-oriented things (various unary coding etc) with hexfiend using binary templates but it quickly gets tedious as the api is currently byte oriented. Sorry for shameless plug but if you want to poke into h264 sps/pps structures etc i recommend a tool i wrote for this https://github.com/wader/fq. It currently has no golumb decoder exposed in the jq language but you can probably write one using binary slicing.

**Comment by kainjow** [comment]
They seem pretty niche? Any other file format that uses them? There are some basic bit functions implemented for the templates, and https://github.com/HexFiend/HexFiend/issues/188 has some other ideas that haven't gotten implemented, so you could check those out. Otherwise could you elaborate on what you're looking for exactly?

**Comment by kainjow** [comment]
I'm going to close this. It seems pretty niche. Feel free to open PRs though to add support.
